name: Update Database
on:
  schedule:
    - cron: "* * * * *"
jobs:
  export:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_DATABASE_ID: ${{ secrets.AIRTABLE_DATABASE_ID }}
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      GH_ACTIONS_PAT: ${{ secrets.GH_ACTIONS_PAT }}
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: pip install airtable-export
      - name: Export Airtable Database
        run: |
          mkdir -p database
          airtable-export --version
          airtable-export --verbose database $AIRTABLE_DATABASE_ID --key=$AIRTABLE_API_KEY  --sqlite database/picks.db Resources Speakers Topics --json --ndjson --yaml
      - name: Generate awesome talks
        run: |
          python3 scripts/generate-content.py
      - name: Commit updated Database
        run: |
          git config --global user.name "Eduardo Ferro"
          git config --global user.email "eferro@eferro.net"
          git add database/picks.db
          git add database/Resources.json
          git add database/Resources.ndjson
          git add database/Resources.yml
          git add database/Speakers.json
          git add database/Speakers.ndjson
          git add database/Speakers.yml
          git add database/Topics.json
          git add database/Topics.ndjson
          git add database/Topics.yml      
          git add index.html
          git commit -m "Exported Airtable Database"
          git pull origin ${{ github.ref }} --rebase
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: ${{ github.ref }}
